#!/usr/bin/env python3
"""
Fill llm_annotations.json from llm-chat-bundle.json using a longest-match lexicon
and unique English headwords (first wins for duplicate zh picks across sentences).

One-off / helper for drafts when no LLM API is wired. Not invoked by mingox by default.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "util"))
from annotate_lib import sentence_body_and_punct  # noqa: E402
from annotate_merge import en_headword_token_ok  # noqa: E402

# (zh, en, ipa, pos, gloss) — zh substring in sentence, en one ASCII token (no hyphens); longest zh first
_LEX_RAW: list[tuple[str, str, str, str, str]] = [
    ("高性能计算", "HPC", "[eɪtʃ piː siː]", "n.", "高性能计算"),
    ("人工智能", "AI", "[eɪ aɪ]", "n.", "人工智能"),
    ("原理", "principle", "[ˈprɪnsəpl]", "n.", "原理"),
    ("为什么", "why", "[waɪ]", "adv.", "为什么"),
    ("回到零", "zero", "[ˈzɪərəʊ]", "n.", "零"),
    ("全球治理", "governance", "[ˈɡʌvənəns]", "n.", "治理"),
    ("国际贸易", "trade", "[treɪd]", "n.", "贸易"),
    ("认知框架", "cognition", "[kɒɡˈnɪʃn]", "n.", "认知"),
    ("操作系统", "system", "[ˈsɪstəm]", "n.", "系统"),
    ("决策底牌", "edge", "[edʒ]", "n.", "底牌"),
    ("零和博弈", "game", "[ɡeɪm]", "n.", "博弈"),
    ("标准化智力", "standardization", "[ˌstændədaɪˈzeɪʃn]", "n.", "标准化"),
    ("人性价值任务", "humanity", "[hjuːˈmænəti]", "n.", "人性"),
    ("半导体存储", "semiconductor", "[ˌsemikənˈdʌktə]", "n.", "半导体"),
    ("加速计算", "computing", "[kəmˈpjuːtɪŋ]", "n.", "计算"),
    ("基础设施", "infrastructure", "[ˈɪnfrəstrʌktʃə]", "n.", "基础设施"),
    ("继任计划", "succession", "[səkˈseʃn]", "n.", "继任"),
    ("持续改进", "improvement", "[ɪmˈpruːvmənt]", "n.", "改进"),
    ("系统性遗忘", "systematic", "[ˌsɪstəˈmætɪk]", "adj.", "系统性"),
    ("不可替代", "irreplaceable", "[ˌɪrɪˈpleɪsəbl]", "adj.", "不可替代"),
    ("核心竞争力", "competence", "[ˈkɒmpɪtəns]", "n.", "竞争力"),
    ("根本性重构", "restructuring", "[riːˈstrʌktʃərɪŋ]", "n.", "重构"),
    ("组织形态", "organization", "[ˌɔːɡənaɪˈzeɪʃn]", "n.", "组织"),
    ("逻辑推理", "logic", "[ˈlɒdʒɪk]", "n.", "逻辑"),
    ("标准化", "standardization", "[ˌstændədaɪˈzeɪʃn]", "n.", "标准化"),
    ("工业化", "industrialization", "[ɪnˌdʌstriəlaɪˈzeɪʃn]", "n.", "工业化"),
    ("廉价商品", "commodity", "[kəˈmɒdəti]", "n.", "商品"),
    ("智力劳动", "intellect", "[ˈɪntəlekt]", "n.", "智力"),
    ("体力劳动", "manual", "[ˈmænjuəl]", "adj.", "体力"),
    ("手工纺织", "handloom", "[ˈhændluːm]", "n.", "手工纺织"),
    ("蒸汽机", "steam", "[stiːm]", "n.", "蒸汽"),
    ("金融分析师", "analyst", "[ˈænəlɪst]", "n.", "分析师"),
    ("品牌策划", "branding", "[ˈbrændɪŋ]", "n.", "策划"),
    ("程序员", "programmer", "[ˈprəʊɡræmə]", "n.", "程序员"),
    ("知识储备", "reserve", "[rɪˈzɜːv]", "n.", "储备"),
    ("计算能力", "calculation", "[ˌkælkjuˈleɪʃn]", "n.", "计算"),
    ("记忆能力", "recollection", "[ˌrekəˈlekʃn]", "n.", "记忆"),
    ("概率计算", "probability", "[ˌprɒbəˈbɪləti]", "n.", "概率"),
    ("逻辑推演", "deduction", "[dɪˈdʌkʃn]", "n.", "推演"),
    ("资本市场", "capital", "[ˈkæpɪtl]", "n.", "资本"),
    ("芯片成本", "chip", "[tʃɪp]", "n.", "芯片"),
    ("游戏显卡", "gaming", "[ˈɡeɪmɪŋ]", "n.", "游戏"),
    ("濒临破产", "bankruptcy", "[ˈbæŋkrʌptsi]", "n.", "破产"),
    ("市值", "valuation", "[ˌvæljuˈeɪʃn]", "n.", "市值"),
    ("护城河", "moat", "[məʊt]", "n.", "护城河"),
    ("掌舵人", "helmsman", "[ˈhelmzmən]", "n.", "掌舵"),
    ("专业赛道", "professional", "[prəˈfeʃənl]", "adj.", "专业"),
    ("深度访谈", "interview", "[ˈɪntəvjuː]", "n.", "访谈"),
    ("商业思维", "business", "[ˈbɪznɪs]", "n.", "商业"),
    ("个人价值", "individual", "[ˌɪndɪˈvɪdʒuəl]", "adj.", "个人"),
    ("工作方式", "manner", "[ˈmænə]", "n.", "方式"),
    ("感知", "perception", "[pəˈsepʃn]", "n.", "感知"),
    ("推理", "reasoning", "[ˈriːzənɪŋ]", "n.", "推理"),
    ("闭环", "loop", "[luːp]", "n.", "闭环"),
    ("功能性", "functional", "[ˈfʌŋkʃənl]", "adj.", "功能的"),
    ("焦虑", "anxiety", "[æŋˈzaɪəti]", "n.", "焦虑"),
    ("拆解", "decompose", "[ˌdiːkəmˈpəʊz]", "v.", "拆解"),
    ("可控", "controllable", "[kənˈtrəʊləbl]", "adj.", "可控"),
    ("羞辱", "humiliation", "[hjuːˌmɪliˈeɪʃn]", "n.", "羞辱"),
    ("尴尬", "embarrassment", "[ɪmˈbærəsmənt]", "n.", "尴尬"),
    ("勇气", "courage", "[ˈkʌrɪdʒ]", "n.", "勇气"),
    ("韧性", "resilience", "[rɪˈzɪliəns]", "n.", "韧性"),
    ("底气", "confidence", "[ˈkɒnfɪdəns]", "n.", "底气"),
    ("不确定性", "uncertainty", "[ʌnˈsɜːtnti]", "n.", "不确定性"),
    ("共情", "empathy", "[ˈempəθi]", "n.", "共情"),
    ("轻描淡写", "understatement", "[ˌʌndəˈsteɪtmənt]", "n.", "轻描淡写"),
    ("合同", "contract", "[ˈkɒntrækt]", "n.", "合同"),
    ("内存带宽", "bandwidth", "[ˈbændwɪdθ]", "n.", "带宽"),
    ("扩产", "expansion", "[ɪkˈspænʃn]", "n.", "扩产"),
    ("利益绑定", "tying", "[ˈtaɪɪŋ]", "n.", "绑定"),
    ("利益算计", "calculus", "[ˈkælkjələs]", "n.", "算计"),
    ("共同愿景", "sharedness", "[ʃeəd]", "n.", "共同"),
    ("合同约束", "contractual", "[kənˈtræktʃuəl]", "adj.", "合同的"),
    ("毫无保留", "unreserved", "[ʌnrɪˈzɜːvd]", "adj.", "毫无保留"),
    ("质疑", "questioning", "[ˈkwestʃənɪŋ]", "n.", "质疑"),
    ("尊重", "respect", "[rɪˈspekt]", "n.", "尊重"),
    ("战略", "strategy", "[ˈstrætədʒi]", "n.", "战略"),
    ("投资", "investment", "[ɪnˈvestmənt]", "n.", "投资"),
    ("长期价值", "longevity", "[lɒnˈdʒevəti]", "n.", "长期"),
    ("下属", "subordinate", "[səˈbɔːdɪnət]", "n.", "下属"),
    ("公开会议", "openness", "[ˈəʊpənnəs]", "n.", "公开"),
    ("不对称", "asymmetry", "[ˌæsɪˈmetri]", "n.", "不对称"),
    ("协作", "collaboration", "[kəˌlæbəˈreɪʃn]", "n.", "协作"),
    ("博弈分析", "analysis", "[əˈnæləsɪs]", "n.", "分析"),
    ("滴水不漏", "watertight", "[ˈwɔːtətaɪt]", "adj.", "滴水不漏"),
    ("稀缺", "scarcity", "[ˈskeəsəti]", "n.", "稀缺"),
    ("背靠背", "solidarity", "[ˌsɒlɪˈdærəti]", "n.", "互信"),
    ("协同", "synergy", "[ˈsɪnədʒi]", "n.", "协同"),
    ("理性", "rationality", "[ˌræʃəˈnæləti]", "n.", "理性"),
    ("意义感", "significance", "[sɪɡˈnɪfɪkəns]", "n.", "意义"),
    ("编程", "programming", "[ˈprəʊɡræmɪŋ]", "n.", "编程"),
    ("暴增", "surge", "[sɜːdʒ]", "v.", "暴增"),
    ("规格", "specification", "[ˌspesɪfɪˈkeɪʃn]", "n.", "规格"),
    ("痛点", "painfulness", "[ˈpeɪnfəlnəs]", "n.", "痛点"),
    ("创新者", "innovator", "[ˈɪnəveɪtə]", "n.", "创新者"),
    ("愿景", "vision", "[ˈvɪʒn]", "n.", "愿景"),
    ("傲慢", "arrogance", "[ˈærəɡəns]", "n.", "傲慢"),
    ("谦逊", "humility", "[hjuːˈmɪləti]", "n.", "谦逊"),
    ("初学者", "beginner", "[bɪˈɡɪnə]", "n.", "初学者"),
    ("贪恋权力", "greed", "[ɡriːd]", "n.", "贪恋"),
    ("接班人", "successor", "[səkˈsesə]", "n.", "接班人"),
    ("洞察力", "insight", "[ˈɪnsaɪt]", "n.", "洞察"),
    ("赋能", "empowerment", "[ɪmˈpaʊəmənt]", "n.", "赋能"),
    ("顾虑", "misgiving", "[mɪsˈɡɪvɪŋ]", "n.", "顾虑"),
    ("优化", "optimization", "[ˌɒptɪmaɪˈzeɪʃn]", "n.", "优化"),
    ("优越感", "superiority", "[suːˌpɪəriˈɒrəti]", "n.", "优越感"),
    ("长期主义", "perseverance", "[ˌpɜːsɪˈvɪərəns]", "n.", "长期"),
    ("重构", "restructure", "[riːˈstrʌktʃə]", "v.", "重构"),
    ("坦诚", "frankness", "[ˈfræŋknəs]", "n.", "坦诚"),
    ("算计", "scheming", "[ˈskiːmɪŋ]", "n.", "算计"),
    ("预期", "expectation", "[ˌekspekˈteɪʃn]", "n.", "预期"),
    ("尊重", "esteem", "[ɪˈstiːm]", "n.", "尊重"),  # duplicate zh - will use first en only
    ("全球化", "globalization", "[ˌɡləʊbəlaɪˈzeɪʃn]", "n.", "全球化"),
    ("哲学", "philosophy", "[fɪˈlɒsəfi]", "n.", "哲学"),
    ("政治", "politics", "[ˈpɒlətɪks]", "n.", "政治"),
    ("经济学", "economics", "[ˌiːkəˈnɒmɪks]", "n.", "经济学"),
    ("企业家", "entrepreneur", "[ˌɒntrəprəˈnɜː]", "n.", "企业家"),
    ("驾驭", "harness", "[ˈhɑːnɪs]", "v.", "驾驭"),
    ("修炼", "cultivation", "[ˌkʌltɪˈveɪʃn]", "n.", "修炼"),
    ("内卷", "involution", "[ˌɪnvəˈluːʃn]", "n.", "内卷"),
    ("智商", "IQ", "[aɪ kjuː]", "n.", "智商"),
    ("人性", "humanity", "[hjuːˈmænəti]", "n.", "人性"),
    ("专家", "expert", "[ˈekspɜːt]", "n.", "专家"),
    ("英伟达", "Nvidia", "[ˈɪnvɪdiə]", "n.", "英伟达"),
    ("廉价", "cheapness", "[tʃiːpnəs]", "n.", "廉价"),
    ("商品", "merchandise", "[ˈmɜːtʃəndaɪz]", "n.", "商品"),
    ("智能", "intelligence", "[ɪnˈtelɪdʒəns]", "n.", "智能"),
    ("准确率", "accuracy", "[ˈækjərəsi]", "n.", "准确率"),
    ("浪漫化", "romanticize", "[rəʊˈmæntɪsaɪz]", "v.", "浪漫化"),
    ("本质", "essence", "[ˈesns]", "n.", "本质"),
    ("计划", "planning", "[ˈplænɪŋ]", "n.", "计划"),
    ("替代", "substitute", "[ˈsʌbstɪtjuːt]", "v.", "替代"),
    ("产量", "output", "[ˈaʊtpʊt]", "n.", "产量"),
    ("革命", "revolution", "[ˌrevəˈluːʃn]", "n.", "革命"),
    ("工业", "industry", "[ˈɪndəstri]", "n.", "工业"),
    ("平台", "platform", "[ˈplætfɔːm]", "n.", "平台"),
    ("单一", "single", "[ˈsɪŋɡl]", "adj.", "单一"),
    ("通用", "versatile", "[ˈvɜːsətaɪl]", "adj.", "通用"),
    ("决策", "decision", "[dɪˈsɪʒn]", "n.", "决策"),
    ("自杀式", "suicidal", "[ˌsuːɪˈsaɪdl]", "adj.", "自杀式"),
    ("毛利", "margin", "[ˈmɑːdʒɪn]", "n.", "毛利"),
    ("止损", "stoploss", "[stɒp]", "n.", "止损"),
    ("压力", "pressure", "[ˈpreʃə]", "n.", "压力"),
    ("跃迁", "leap", "[liːp]", "n.", "跃迁"),
    ("底座", "foundation", "[faʊnˈdeɪʃn]", "n.", "底座"),
    ("属性", "attribute", "[ˈætrɪbjuːt]", "n.", "属性"),
    ("痛苦", "pain", "[peɪn]", "n.", "痛苦"),
    ("挫折", "setback", "[ˈsetbæk]", "n.", "挫折"),
    ("精力", "energy", "[ˈenədʒi]", "n.", "精力"),
    ("粉身碎骨", "shattered", "[ˈʃætəd]", "adj.", "粉碎"),
    ("信任", "trust", "[trʌst]", "n.", "信任"),
    ("约束", "constraint", "[kənˈstreɪnt]", "n.", "约束"),
    ("底线", "baseline", "[ˈbeɪslaɪn]", "n.", "底线"),
    ("上限", "ceiling", "[ˈsiːlɪŋ]", "n.", "上限"),
    ("本质", "nature", "[ˈneɪtʃə]", "n.", "本质"),
    ("生命", "vitality", "[vaɪˈtæləti]", "n.", "生命"),
    ("超人", "superhuman", "[ˌsuːpəˈhjuːmən]", "adj.", "超人"),
    ("万亿", "trillion", "[ˈtrɪljən]", "n.", "万亿"),
    ("专业", "expertise", "[ˌekspɜːˈtiːz]", "n.", "专业"),
    ("方向", "direction", "[daɪˈrekʃn]", "n.", "方向"),
    ("进化", "evolution", "[ˌiːvəˈluːʃn]", "n.", "进化"),
    ("顶尖", "apex", "[ˈeɪpeks]", "n.", "顶尖"),
    ("工具", "tool", "[tuːl]", "n.", "工具"),
    ("意义", "meaning", "[ˈmiːnɪŋ]", "n.", "意义"),
    ("社会", "society", "[səˈsaɪəti]", "n.", "社会"),
    ("价值", "value", "[ˈvæljuː]", "n.", "价值"),
    ("初心", "originality", "[ərɪdʒəˈnæləti]", "n.", "初心"),
    ("餐厅", "restaurant", "[ˈrestrɒnt]", "n.", "餐厅"),
    ("心态", "mindset", "[ˈmaɪndset]", "n.", "心态"),
    ("权力", "authority", "[ɔːˈθɒrəti]", "n.", "权力"),
    ("永生", "immortality", "[ˌɪmɔːˈtæləti]", "n.", "永生"),
    ("传递", "transfer", "[trænsˈfɜː]", "v.", "传递"),
    ("技能", "skill", "[skɪl]", "n.", "技能"),
    ("经验", "experience", "[ɪkˈspɪəriəns]", "n.", "经验"),
    ("指令", "directive", "[dɪˈrektɪv]", "n.", "指令"),
    ("依据", "basis", "[ˈbeɪsɪs]", "n.", "依据"),
    ("分享", "sharing", "[ˈʃeərɪŋ]", "n.", "分享"),
    ("思维", "thinking", "[ˈθɪŋkɪŋ]", "n.", "思维"),
    ("前提", "premise", "[ˈpremɪs]", "n.", "前提"),
    ("困住", "trap", "[træp]", "v.", "困住"),
    ("掌握", "mastery", "[ˈmɑːstəri]", "n.", "掌握"),
    ("核心", "core", "[kɔː]", "n.", "核心"),
    ("精力", "vigor", "[ˈvɪɡə]", "n.", "精力"),
    ("前者", "former", "[ˈfɔːmə]", "n.", "前者"),
    ("后者", "latter", "[ˈlætə]", "n.", "后者"),
    ("规划", "blueprint", "[ˈbluːprɪnt]", "n.", "规划"),
    ("站稳", "steadfast", "[ˈstedfɑːst]", "adj.", "站稳"),
    ("客户", "client", "[ˈklaɪənt]", "n.", "客户"),
    ("同事", "colleague", "[ˈkɒliːɡ]", "n.", "同事"),
    ("伙伴", "partner", "[ˈpɑːtnə]", "n.", "伙伴"),
    ("尊重", "deference", "[ˈdefərəns]", "n.", "尊重"),
    ("时代", "era", "[ˈɪərə]", "n.", "时代"),
    ("变革", "transformation", "[ˌtrænsfəˈmeɪʃn]", "n.", "变革"),
    ("重塑", "reshape", "[riːˈʃeɪp]", "v.", "重塑"),
    ("挑战", "challenge", "[ˈtʃælɪndʒ]", "n.", "挑战"),
    ("招生", "enrollment", "[ɪnˈrəʊlmənt]", "n.", "招生"),
    ("名额", "quota", "[ˈkwəʊtə]", "n.", "名额"),
    ("海报", "poster", "[ˈpəʊstə]", "n.", "海报"),
    ("二维码", "qrcode", "[kjuː ɑː]", "n.", "二维码"),
    ("咨询", "consultation", "[ˌkɒnsəlˈteɪʃn]", "n.", "咨询"),
    ("访谈", "interview", "[ˈɪntəvjuː]", "n.", "访谈"),
    ("程序员", "coder", "[ˈkəʊdə]", "n.", "程序员"),
    ("暴涨", "soar", "[sɔː]", "v.", "暴涨"),
    ("版图", "territory", "[ˈterətri]", "n.", "版图"),
    ("矩阵", "matrix", "[ˈmeɪtrɪks]", "n.", "矩阵"),
    ("公众号", "officialdom", "[əˈfɪʃldəm]", "n.", "官方"),
    ("方法论", "methodology", "[ˌmeθəˈdɒlədʒi]", "n.", "方法论"),
    ("职场", "workplace", "[ˈwɜːkpleɪs]", "n.", "职场"),
    ("人际关系", "interpersonal", "[ˌɪntəˈpɜːsənl]", "adj.", "人际"),
    ("点赞", "thumbsup", "[θʌmz]", "n.", "点赞"),
    ("笔记侠", "Notesman", "[nəʊts]", "n.", "笔记侠"),
    ("这件事", "matter", "[ˈmætə]", "n.", "这件事"),
    ("条件", "condition", "[kənˈdɪʃn]", "n.", "条件"),
    ("来源", "provenance", "[ˈprɒvənəns]", "n.", "来源"),
    ("排版", "typesetting", "[ˈtaɪpsetɪŋ]", "n.", "排版"),
    ("阅读", "reading", "[ˈriːdɪŋ]", "n.", "阅读"),
    ("启发", "enlightenment", "[ɪnˈlaɪtnmənt]", "n.", "启发"),
    ("文章", "article", "[ˈɑːtɪkl]", "n.", "文章"),
    ("经历", "journey", "[ˈdʒɜːni]", "n.", "经历"),
    ("法则", "principle", "[ˈprɪnsəpl]", "n.", "法则"),
    ("生存", "survival", "[səˈvaɪvl]", "n.", "生存"),
    ("代码", "code", "[kəʊd]", "n.", "代码"),
    ("财报", "financials", "[faɪˈnænʃlz]", "n.", "财报"),
    ("人工", "manpower", "[ˈmænpaʊə]", "n.", "人工"),
    ("分钟", "minute", "[ˈmɪnɪt]", "n.", "分钟"),
    ("成本", "cost", "[kɒst]", "n.", "成本"),
    ("记忆", "recall", "[rɪˈkɔːl]", "n.", "记忆"),
    ("算力", "compute", "[kəmˈpjuːt]", "n.", "算力"),
    ("记忆", "remembrance", "[rɪˈmembrəns]", "n.", "记忆"),
    ("绑定", "binding", "[ˈbaɪndɪŋ]", "n.", "绑定"),
    ("劳动力", "workforce", "[ˈwɜːkfɔːs]", "n.", "劳动力"),
    ("解放", "liberation", "[ˌlɪbəˈreɪʃn]", "n.", "解放"),
    ("遗忘", "forgetting", "[fəˈɡetɪŋ]", "n.", "遗忘"),
    ("诞生", "birth", "[bɜːθ]", "n.", "诞生"),
    ("脚跟", "foothold", "[ˈfʊthəʊld]", "n.", "脚跟"),
    ("梦想", "dream", "[driːm]", "n.", "梦想"),
    ("自杀", "suicide", "[ˈsuːɪsaɪd]", "n.", "自杀"),
    ("放进", "embed", "[ɪmˈbed]", "v.", "嵌入"),
    ("推出", "rollout", "[ˈrəʊlaʊt]", "n.", "推出"),
    ("声音", "voice", "[vɔɪs]", "n.", "声音"),
    ("局面", "situation", "[ˌsɪtʃuˈeɪʃn]", "n.", "局面"),
    ("十几年", "decade", "[ˈdekeɪd]", "n.", "十年"),
    ("时刻", "moment", "[ˈməʊmənt]", "n.", "时刻"),
    ("有意思", "intriguing", "[ɪnˈtriːɡɪŋ]", "adj.", "有意思"),
    ("学习", "learning", "[ˈlɜːnɪŋ]", "n.", "学习"),
    ("快速", "swift", "[swɪft]", "adj.", "快速"),
    ("失败", "failure", "[ˈfeɪljə]", "n.", "失败"),
    ("小事", "trivial", "[ˈtrɪviəl]", "adj.", "小事"),
    ("行动", "action", "[ˈækʃn]", "n.", "行动"),
    ("精准", "precise", "[prɪˈsaɪs]", "adj.", "精准"),
    ("完美", "perfect", "[ˈpɜːfɪkt]", "adj.", "完美"),
    ("大概率", "likelihood", "[ˈlaɪklihʊd]", "n.", "概率"),
    ("坚定", "steadfastness", "[ˈstedfɑːst]", "adj.", "坚定"),
    ("超级", "supercomputer", "[ˈsuːpəkəmpjuːtə]", "n.", "超算"),
    ("商用", "commercial", "[kəˈmɜːʃl]", "adj.", "商用"),
    ("数十亿", "billions", "[ˈbɪljənz]", "n.", "数十亿"),
    ("地位", "status", "[ˈsteɪtəs]", "n.", "地位"),
    ("行业", "sector", "[ˈsektə]", "n.", "行业"),
    ("管理", "management", "[ˈmænɪdʒmənt]", "n.", "管理"),
    ("会议", "meeting", "[ˈmiːtɪŋ]", "n.", "会议"),
    ("沟通", "communication", "[kəˌmjuːnɪˈkeɪʃn]", "n.", "沟通"),
    ("恰恰", "precisely", "[prɪˈsaɪsli]", "adv.", "恰恰"),
    ("台面", "tabletop", "[ˈteɪbltɒp]", "n.", "台面"),
    ("诉求", "appeal", "[əˈpiːl]", "n.", "诉求"),
    ("难处", "plight", "[plaɪt]", "n.", "难处"),
    ("参与", "participation", "[pɑːˌtɪsɪˈpeɪʃn]", "n.", "参与"),
    ("前提", "precondition", "[ˌpriːkənˈdɪʃn]", "n.", "前提"),
    ("利益", "stake", "[steɪk]", "n.", "利益"),
    ("账", "ledger", "[ˈledʒə]", "n.", "账目"),
    ("打通", "connect", "[kəˈnekt]", "v.", "打通"),
    ("重量", "weight", "[weɪt]", "n.", "重量"),
    ("好奇", "curiosity", "[ˌkjʊəriˈɒsəti]", "n.", "好奇"),
    ("凭什么", "grounds", "[ɡraʊndz]", "n.", "依据"),
    ("简单", "simplicity", "[sɪmˈplɪsəti]", "n.", "简单"),
    ("定义", "define", "[dɪˈfaɪn]", "v.", "定义"),
    ("暴增", "explosion", "[ɪkˈspləʊʒn]", "n.", "暴增"),
    ("本质", "entity", "[ˈentəti]", "n.", "本质"),
    ("目标", "objective", "[əbˈdʒektɪv]", "n.", "目标"),
    ("顶尖", "apex", "[ˈeɪpeks]", "n.", "顶尖"),
    ("艰难", "arduous", "[ˈɑːdʒuəs]", "adj.", "艰难"),
    ("愿望", "aspiration", "[ˌæspəˈreɪʃn]", "n.", "愿望"),
    ("用户", "user", "[ˈjuːzə]", "n.", "用户"),
    ("伟大", "greatness", "[ˈɡreɪtnəs]", "n.", "伟大"),
    ("强大", "powerful", "[ˈpaʊəfl]", "adj.", "强大"),
    ("方向", "bearing", "[ˈbeərɪŋ]", "n.", "方向"),
    ("厕所", "restroom", "[ˈrestruːm]", "n.", "厕所"),
    ("成功者", "achiever", "[əˈtʃiːvə]", "n.", "成功者"),
    ("理解", "comprehension", "[ˌkɒmprɪˈhenʃn]", "n.", "理解"),
    ("闻名", "renown", "[rɪˈnaʊn]", "n.", "闻名"),
    ("答案", "answer", "[ˈɑːnsə]", "n.", "答案"),
    ("关心", "concern", "[kənˈsɜːn]", "n.", "关心"),
    ("未来", "future", "[ˈfjuːtʃə]", "n.", "未来"),
    ("公开", "public", "[ˈpʌblɪk]", "adj.", "公开"),
    ("推理", "inference", "[ˈɪnfərəns]", "n.", "推理"),
    ("摊开", "expose", "[ɪkˈspəʊz]", "v.", "摊开"),
    ("停留", "linger", "[ˈlɪŋɡə]", "v.", "停留"),
    ("讨厌", "dislike", "[dɪsˈlaɪk]", "v.", "讨厌"),
    ("默认", "presume", "[prɪˈzjuːm]", "v.", "默认"),
    ("做法", "practice", "[ˈpræktɪs]", "n.", "做法"),
    ("从头", "afresh", "[əˈfreʃ]", "adv.", "从头"),
    ("技术", "technology", "[tekˈnɒlədʒi]", "n.", "技术"),
    ("成长", "growth", "[ɡrəʊθ]", "n.", "成长"),
    ("更新", "update", "[ʌpˈdeɪt]", "n.", "更新"),
    ("决定", "determine", "[dɪˈtɜːmɪn]", "v.", "决定"),
    ("统计", "statistics", "[stəˈtɪstɪks]", "n.", "统计"),
    ("模板", "template", "[ˈtempleɪt]", "n.", "模板"),
    ("报表", "reporting", "[rɪˈpɔːtɪŋ]", "n.", "报表"),
    ("需求", "demand", "[dɪˈmɑːnd]", "n.", "需求"),
    ("沟通", "dialogue", "[ˈdaɪəlɒɡ]", "n.", "沟通"),
    ("复杂", "complexity", "[kəmˈpleksəti]", "n.", "复杂"),
    ("温度", "warmth", "[wɔːmθ]", "n.", "温度"),
    ("服务", "service", "[ˈsɜːvɪs]", "n.", "服务"),
    ("高效", "efficient", "[ɪˈfɪʃnt]", "adj.", "高效"),
    ("小聪明", "cleverness", "[ˈklevənəs]", "n.", "小聪明"),
    ("实用", "practical", "[ˈpræktɪkl]", "adj.", "实用"),
    ("建议", "suggestion", "[səˈdʒestʃn]", "n.", "建议"),
    ("角度", "angle", "[ˈæŋɡl]", "n.", "角度"),
    ("底线", "threshold", "[ˈθreʃhəʊld]", "n.", "底线"),
    ("初学者心态", "novice", "[ˈnɒvɪs]", "n.", "初学者"),
    ("深嵌", "embedded", "[ɪmˈbedɪd]", "adj.", "嵌入"),
    ("科技", "technics", "[ˈteknɪks]", "n.", "科技"),
    ("经济", "economy", "[ɪˈkɒnəmi]", "n.", "经济"),
    ("政治", "polity", "[ˈpɒləti]", "n.", "政治"),
    ("环境", "environment", "[ɪnˈvaɪrənmənt]", "n.", "环境"),
    ("逻辑", "logic", "[ˈlɒdʒɪk]", "n.", "逻辑"),
    ("智能商业", "smartness", "[ˈsmɑːtnəs]", "n.", "智能"),
    ("文明", "civilization", "[ˌsɪvəlaɪˈzeɪʃn]", "n.", "文明"),
    ("进程", "process", "[ˈprəʊses]", "n.", "进程"),
    ("格局", "landscape", "[ˈlændskeɪp]", "n.", "格局"),
    ("政策", "policy", "[ˈpɒləsi]", "n.", "政策"),
    ("完整", "integrity", "[ɪnˈteɡrəti]", "n.", "完整"),
    ("世界", "world", "[wɜːld]", "n.", "世界"),
    ("中国", "China", "[ˈtʃaɪnə]", "n.", "中国"),
    ("心力", "psyche", "[ˈsaɪki]", "n.", "心力"),
    ("穿越", "traverse", "[trəˈvɜːs]", "v.", "穿越"),
    ("大陆", "continent", "[ˈkɒntɪnənt]", "n.", "大陆"),
    ("主理人", "curator", "[kjʊˈreɪtə]", "n.", "主理人"),
    ("详情", "details", "[ˈdiːteɪlz]", "n.", "详情"),
    ("参考", "reference", "[ˈrefrəns]", "n.", "参考"),
    ("资料", "materials", "[məˈtɪəriəlz]", "n.", "资料"),
    ("阅读", "readership", "[ˈriːdəʃɪp]", "n.", "阅读"),
    ("推荐", "recommendation", "[ˌrekəmenˈdeɪʃn]", "n.", "推荐"),
    ("演讲", "speech", "[spiːtʃ]", "n.", "演讲"),
    ("淘汰", "elimination", "[ɪˌlɪmɪˈneɪʃn]", "n.", "淘汰"),
    ("开战", "showdown", "[ˈʃəʊdaʊn]", "n.", "开战"),
    ("子弹", "bullet", "[ˈbʊlɪt]", "n.", "子弹"),
    ("效率", "efficiency", "[ɪˈfɪʃnsi]", "n.", "效率"),
    ("成长", "maturation", "[ˌmætʃuˈreɪʃn]", "n.", "成长"),
    ("吃透", "digest", "[daɪˈdʒest]", "v.", "吃透"),
    ("关注", "follow", "[ˈfɒləʊ]", "v.", "关注"),
    ("分享", "share", "[ʃeə]", "v.", "分享"),
    ("对内", "internal", "[ɪnˈtɜːnl]", "adj.", "对内"),
    ("一样", "likewise", "[ˈlaɪkwaɪz]", "adv.", "同样"),
    ("注意", "note", "[nəʊt]", "n.", "注意"),
    ("做事", "doing", "[ˈduːɪŋ]", "n.", "做事"),
    ("能力", "capability", "[ˌkeɪpəˈbɪləti]", "n.", "能力"),
    ("理解", "grasp", "[ɡrɑːsp]", "n.", "理解"),
    ("协同", "coordination", "[kəʊˌɔːdɪˈneɪʃn]", "n.", "协同"),
    ("欢迎", "welcome", "[ˈwelkəm]", "n.", "欢迎"),
]

for _lz, _le, *_ in _LEX_RAW:
    if not en_headword_token_ok(_le):
        raise ValueError(f"lexicon en invalid: {_le!r} (zh={_lz!r})")


def _lex_sorted() -> list[tuple[str, str, str, str, str]]:
    return sorted(_LEX_RAW, key=lambda x: len(x[0]), reverse=True)


def pick_for_sentence(body: str, used_en: set[str]) -> tuple[str, str, str, str, str] | None:
    for zh, en, ipa, pos, gloss in _lex_sorted():
        if zh not in body:
            continue
        key = en.lower()
        if key in used_en:
            continue
        return (zh, en, ipa, pos, gloss)
    return None


def main() -> int:
    ap = argparse.ArgumentParser(description="Fill annotations from bundle + lexicon.")
    ap.add_argument("--bundle", type=Path, required=True)
    ap.add_argument("-o", "--output", type=Path, required=True)
    args = ap.parse_args()
    data = json.loads(args.bundle.read_text(encoding="utf-8"))
    sents = data.get("sentences") or []
    used: set[str] = set()
    annotations: list[dict] = []
    for item in sents:
        i = int(item["i"])
        text = str(item.get("text") or "")
        body, _p = sentence_body_and_punct(text)
        if not body.strip():
            annotations.append({"i": i, "skip": True})
            continue
        picked = pick_for_sentence(body, used)
        if not picked:
            annotations.append({"i": i, "skip": True})
            continue
        zh, en, ipa, pos, gloss = picked
        used.add(en.lower())
        annotations.append(
            {
                "i": i,
                "zh": zh,
                "en": en,
                "ipa": ipa if ipa.startswith("[") else f"[{ipa}]",
                "pos": pos,
                "gloss": gloss,
            }
        )
    out = {"version": 1, "annotations": annotations}
    args.output.write_text(json.dumps(out, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    n_skip = sum(1 for a in annotations if a.get("skip"))
    n_ok = len(annotations) - n_skip
    print(f"wrote {args.output} annotated={n_ok} skip={n_skip} total={len(annotations)}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
