import json

annotations = [
    {"i": 0, "skip": True},
    {"i": 1, "skip": True},
    {"i": 2, "zh": "突然", "en": "suddenly", "ipa": "[ˈsʌdənli]", "pos": "adv.", "gloss": "突然地"},
    {"i": 3, "zh": "尴尬", "en": "awkward", "ipa": "[ˈɔːkwərd]", "pos": "adj.", "gloss": "尴尬的"},
    {"i": 4, "zh": "故意", "en": "deliberate", "ipa": "[dɪˈlɪbərət]", "pos": "adj.", "gloss": "故意的"},
    {"i": 5, "zh": "持续", "en": "persist", "ipa": "[pəˈsɪst]", "pos": "v.", "gloss": "持续；坚持"},
    {"i": 6, "zh": "征兆", "en": "symptom", "ipa": "[ˈsɪmptəm]", "pos": "n.", "gloss": "征兆；症状"},
    {"i": 7, "zh": "臭味", "en": "odor", "ipa": "[ˈoʊdər]", "pos": "n.", "gloss": "气味；臭味"},
    {"i": 8, "zh": "消失", "en": "vanish", "ipa": "[ˈvænɪʃ]", "pos": "v.", "gloss": "消失"},
    {"i": 9, "zh": "焦虑", "en": "anxiety", "ipa": "[æŋˈzaɪəti]", "pos": "n.", "gloss": "焦虑；忧虑"},
    {"i": 10, "zh": "频繁", "en": "frequent", "ipa": "[ˈfriːkwənt]", "pos": "adj.", "gloss": "频繁的"},
    {"i": 11, "zh": "担心", "en": "concern", "ipa": "[kənˈsɜːrn]", "pos": "v.", "gloss": "担心；关注"},
    {"i": 12, "zh": "频率", "en": "frequency", "ipa": "[ˈfriːkwənsi]", "pos": "n.", "gloss": "频率"},
    {"i": 13, "zh": "内向", "en": "introverted", "ipa": "[ˌɪntrəˈvɜːrtɪd]", "pos": "adj.", "gloss": "内向的"},
    {"i": 14, "zh": "症状", "en": "syndrome", "ipa": "[ˈsɪndroʊm]", "pos": "n.", "gloss": "综合征；症状群"},
    {"i": 15, "zh": "消化", "en": "digestive", "ipa": "[daɪˈdʒestɪv]", "pos": "adj.", "gloss": "消化的"},
    {"i": 16, "zh": "问题", "en": "abnormality", "ipa": "[ˌæbnɔːrˈmæləti]", "pos": "n.", "gloss": "异常；问题"},
    {"i": 17, "zh": "宣传", "en": "publicity", "ipa": "[pʌbˈlɪsəti]", "pos": "n.", "gloss": "宣传；公开"},
    {"i": 18, "skip": True},
    {"i": 19, "zh": "典型", "en": "typical", "ipa": "[ˈtɪpɪkl]", "pos": "adj.", "gloss": "典型的"},
    {"i": 20, "zh": "一模一样", "en": "identical", "ipa": "[aɪˈdentɪkl]", "pos": "adj.", "gloss": "完全相同的"},
    {"i": 21, "zh": "规律", "en": "regular", "ipa": "[ˈreɡjələr]", "pos": "adj.", "gloss": "规律的；定期的"},
    {"i": 22, "skip": True},
    {"i": 23, "zh": "崩溃", "en": "collapse", "ipa": "[kəˈlæps]", "pos": "v.", "gloss": "崩溃；瓦解"},
    {"i": 24, "zh": "无望", "en": "hopeless", "ipa": "[ˈhoʊpləs]", "pos": "adj.", "gloss": "无望的"},
    {"i": 25, "zh": "恐惧", "en": "terror", "ipa": "[ˈterər]", "pos": "n.", "gloss": "恐惧；恐慌"},
    {"i": 26, "skip": True},
    {"i": 27, "zh": "常见", "en": "prevalent", "ipa": "[ˈprevələnt]", "pos": "adj.", "gloss": "流行的；常见的"},
    {"i": 28, "zh": "患病率", "en": "prevalence", "ipa": "[ˈprevələns]", "pos": "n.", "gloss": "患病率；流行率"},
    {"i": 29, "zh": "诊疗", "en": "diagnosis", "ipa": "[ˌdaɪəɡˈnoʊsɪs]", "pos": "n.", "gloss": "诊断"},
    {"i": 30, "zh": "预期寿命", "en": "longevity", "ipa": "[lɒnˈdʒevəti]", "pos": "n.", "gloss": "寿命；长寿"},
    {"i": 31, "zh": "确诊", "en": "confirm", "ipa": "[kənˈfɜːrm]", "pos": "v.", "gloss": "确认；确诊"},
    {"i": 32, "zh": "担惊受怕", "en": "panic", "ipa": "[ˈpænɪk]", "pos": "v.", "gloss": "恐慌；害怕"},
    {"i": 33, "zh": "卷土重来", "en": "resurge", "ipa": "[rɪˈsɜːrdʒ]", "pos": "v.", "gloss": "再起；卷土重来"},
    {"i": 34, "zh": "学业压力", "en": "academic", "ipa": "[ˌækəˈdemɪk]", "pos": "adj.", "gloss": "学业的；学术的"},
    {"i": 35, "zh": "尖锐", "en": "sharp", "ipa": "[ʃɑːrp]", "pos": "adj.", "gloss": "尖锐的；剧烈的"},
    {"i": 36, "skip": True},
    {"i": 37, "zh": "愈发", "en": "increasingly", "ipa": "[ɪnˈkriːsɪŋli]", "pos": "adv.", "gloss": "越来越；愈发"},
    {"i": 38, "zh": "意识到", "en": "realize", "ipa": "[ˈriːəlaɪz]", "pos": "v.", "gloss": "意识到；实现"},
    {"i": 39, "zh": "盯着", "en": "stare", "ipa": "[ster]", "pos": "v.", "gloss": "盯着看；凝视"},
    {"i": 40, "zh": "记忆", "en": "memory", "ipa": "[ˈmeməri]", "pos": "n.", "gloss": "记忆；回忆"},
    {"i": 41, "skip": True},
    {"i": 42, "skip": True},
    {"i": 43, "zh": "收缩", "en": "contraction", "ipa": "[kənˈtrækʃn]", "pos": "n.", "gloss": "收缩；紧缩"},
    {"i": 44, "zh": "明显", "en": "obvious", "ipa": "[ˈɑːbviəs]", "pos": "adj.", "gloss": "明显的"},
    {"i": 45, "zh": "猜测", "en": "speculate", "ipa": "[ˈspekjuleɪt]", "pos": "v.", "gloss": "猜测；推测"},
    {"i": 46, "zh": "控制", "en": "control", "ipa": "[kənˈtroʊl]", "pos": "v.", "gloss": "控制；支配"},
    {"i": 47, "zh": "密闭", "en": "enclosed", "ipa": "[ɪnˈkloʊzd]", "pos": "adj.", "gloss": "封闭的；密闭的"},
    {"i": 48, "skip": True},
    {"i": 49, "zh": "影响", "en": "affect", "ipa": "[əˈfekt]", "pos": "v.", "gloss": "影响；感动"},
    {"i": 50, "skip": True},
    {"i": 51, "zh": "不可思议", "en": "inconceivable", "ipa": "[ˌɪnkənˈsiːvəbl]", "pos": "adj.", "gloss": "不可思议的"},
    {"i": 52, "skip": True},
    {"i": 53, "skip": True},
    {"i": 54, "zh": "围绕", "en": "revolve", "ipa": "[rɪˈvɑːlv]", "pos": "v.", "gloss": "围绕；旋转"},
    {"i": 55, "zh": "验证", "en": "verify", "ipa": "[ˈverɪfaɪ]", "pos": "v.", "gloss": "验证；核实"},
    {"i": 56, "zh": "查出", "en": "detect", "ipa": "[dɪˈtekt]", "pos": "v.", "gloss": "查出；探测"},
    {"i": 57, "zh": "确诊", "en": "diagnose", "ipa": "[ˈdaɪəɡnoʊz]", "pos": "v.", "gloss": "诊断；确诊"},
    {"i": 58, "skip": True},
    {"i": 59, "skip": True},
    {"i": 60, "zh": "异常", "en": "exception", "ipa": "[ɪkˈsepʃn]", "pos": "n.", "gloss": "异常；例外"},
    {"i": 61, "skip": True},
    {"i": 62, "zh": "规律", "en": "pattern", "ipa": "[ˈpætərn]", "pos": "n.", "gloss": "规律；模式"},
    {"i": 63, "zh": "幽门", "en": "bacteria", "ipa": "[bækˈtɪriə]", "pos": "n.", "gloss": "细菌"},
    {"i": 64, "skip": True},
    {"i": 65, "skip": True},
    {"i": 66, "zh": "常规", "en": "conventional", "ipa": "[kənˈvenʃənl]", "pos": "adj.", "gloss": "常规的；传统的"},
    {"i": 67, "zh": "病症", "en": "disorder", "ipa": "[dɪsˈɔːrdər]", "pos": "n.", "gloss": "病症；紊乱"},
    {"i": 68, "zh": "客观", "en": "objective", "ipa": "[əbˈdʒektɪv]", "pos": "adj.", "gloss": "客观的"},
    {"i": 69, "zh": "盲区", "en": "blindspot", "ipa": "[ˈblaɪndspɑːt]", "pos": "n.", "gloss": "盲区；盲点"},
    {"i": 70, "zh": "得知", "en": "learn", "ipa": "[lɜːrn]", "pos": "v.", "gloss": "得知；学习"},
    {"i": 71, "skip": True},
    {"i": 72, "zh": "频率", "en": "interval", "ipa": "[ˈɪntərvl]", "pos": "n.", "gloss": "间隔；频率"},
    {"i": 73, "skip": True},
    {"i": 74, "skip": True},
    {"i": 75, "zh": "注意力", "en": "attention", "ipa": "[əˈtenʃn]", "pos": "n.", "gloss": "注意力"},
    {"i": 76, "zh": "饮食", "en": "dietary", "ipa": "[ˈdaɪəteri]", "pos": "adj.", "gloss": "饮食的"},
    {"i": 77, "zh": "无济于事", "en": "futile", "ipa": "[ˈfjuːtl]", "pos": "adj.", "gloss": "无效的；无用的"},
    {"i": 78, "zh": "担心", "en": "dread", "ipa": "[dred]", "pos": "v.", "gloss": "担忧；害怕"},
    {"i": 79, "zh": "过往", "en": "previous", "ipa": "[ˈpriːviəs]", "pos": "adj.", "gloss": "以往的；从前的"},
    {"i": 80, "zh": "缓解", "en": "relieve", "ipa": "[rɪˈliːv]", "pos": "v.", "gloss": "缓解；减轻"},
    {"i": 81, "skip": True},
    {"i": 82, "skip": True},
    {"i": 83, "skip": True},
    {"i": 84, "zh": "就诊", "en": "consultation", "ipa": "[ˌkɑːnslˈteɪʃn]", "pos": "n.", "gloss": "就诊；咨询"},
    {"i": 85, "skip": True},
    {"i": 86, "zh": "暗示", "en": "suggestion", "ipa": "[səˈdʒestʃən]", "pos": "n.", "gloss": "暗示；建议"},
    {"i": 87, "skip": True},
    {"i": 88, "zh": "愣住", "en": "stunned", "ipa": "[stʌnd]", "pos": "adj.", "gloss": "愣住的；震惊的"},
    {"i": 89, "zh": "尘埃落定", "en": "settled", "ipa": "[ˈsetld]", "pos": "adj.", "gloss": "尘埃落定的；已解决的"},
    {"i": 90, "skip": True},
    {"i": 91, "zh": "依赖", "en": "rely", "ipa": "[rɪˈlaɪ]", "pos": "v.", "gloss": "依赖；依靠"},
    {"i": 92, "zh": "评估", "en": "evaluate", "ipa": "[ɪˈvæljueɪt]", "pos": "v.", "gloss": "评估；评价"},
    {"i": 93, "zh": "标志物", "en": "marker", "ipa": "[ˈmɑːrkər]", "pos": "n.", "gloss": "标志物；标记"},
    {"i": 94, "zh": "交互", "en": "interact", "ipa": "[ˌɪntərˈækt]", "pos": "v.", "gloss": "交互；互动"},
    {"i": 95, "zh": "通路", "en": "pathway", "ipa": "[ˈpæθweɪ]", "pos": "n.", "gloss": "通路；路径"},
    {"i": 96, "zh": "递质", "en": "transmitter", "ipa": "[trænzˈmɪtər]", "pos": "n.", "gloss": "递质；传送者"},
    {"i": 97, "zh": "情绪", "en": "emotional", "ipa": "[ɪˈmoʊʃənl]", "pos": "adj.", "gloss": "情绪的；情感的"},
    {"i": 98, "zh": "受到影响", "en": "impair", "ipa": "[ɪmˈper]", "pos": "v.", "gloss": "损害；影响"},
    {"i": 99, "zh": "作祟", "en": "psychological", "ipa": "[ˌsaɪkəˈlɑːdʒɪkl]", "pos": "adj.", "gloss": "心理的"},
    {"i": 100, "zh": "霸凌", "en": "bully", "ipa": "[ˈbʊli]", "pos": "v.", "gloss": "霸凌；欺负"},
    {"i": 101, "skip": True},
    {"i": 102, "skip": True},
    {"i": 103, "skip": True},
    {"i": 104, "zh": "创伤", "en": "trauma", "ipa": "[ˈtraʊmə]", "pos": "n.", "gloss": "创伤；外伤"},
    {"i": 105, "zh": "逃离", "en": "escape", "ipa": "[ɪˈskeɪp]", "pos": "v.", "gloss": "逃离；逃避"},
    {"i": 106, "zh": "复盘", "en": "review", "ipa": "[rɪˈvjuː]", "pos": "v.", "gloss": "复盘；回顾"},
    {"i": 107, "zh": "高频", "en": "peak", "ipa": "[piːk]", "pos": "n.", "gloss": "高峰；峰值"},
    {"i": 108, "skip": True},
    {"i": 109, "skip": True},
    {"i": 110, "skip": True},
    {"i": 111, "skip": True},
    {"i": 112, "skip": True},
    {"i": 113, "zh": "严重", "en": "severe", "ipa": "[sɪˈvɪr]", "pos": "adj.", "gloss": "严重的；剧烈的"},
    {"i": 114, "zh": "欣欣向荣", "en": "prosperous", "ipa": "[ˈprɑːspərəs]", "pos": "adj.", "gloss": "繁荣的；兴旺的"},
    {"i": 115, "zh": "心动", "en": "tempt", "ipa": "[tempt]", "pos": "v.", "gloss": "诱惑；心动"},
    {"i": 116, "zh": "稳定", "en": "stable", "ipa": "[ˈsteɪbl]", "pos": "adj.", "gloss": "稳定的"},
    {"i": 117, "zh": "反作用", "en": "counteract", "ipa": "[ˌkaʊntərˈækt]", "pos": "v.", "gloss": "抵消；反作用于"},
    {"i": 118, "zh": "耗竭", "en": "depletion", "ipa": "[dɪˈpliːʃn]", "pos": "n.", "gloss": "耗竭；消耗"},
    {"i": 119, "skip": True},
    {"i": 120, "zh": "访问", "en": "interview", "ipa": "[ˈɪntərvjuː]", "pos": "v.", "gloss": "访问；采访"},
    {"i": 121, "skip": True},
    {"i": 122, "zh": "场合", "en": "occasion", "ipa": "[əˈkeɪʒn]", "pos": "n.", "gloss": "场合；时机"},
    {"i": 123, "zh": "暗示", "en": "hint", "ipa": "[hɪnt]", "pos": "n.", "gloss": "暗示；提示"},
    {"i": 124, "zh": "本科线", "en": "undergraduate", "ipa": "[ˌʌndərˈɡrædʒuət]", "pos": "n.", "gloss": "本科生；本科的"},
    {"i": 125, "skip": True},
    {"i": 126, "zh": "恐慌", "en": "frantic", "ipa": "[ˈfræntɪk]", "pos": "adj.", "gloss": "恐慌的；慌乱的"},
    {"i": 127, "zh": "宅", "en": "confine", "ipa": "[kənˈfaɪn]", "pos": "v.", "gloss": "限制；禁闭"},
    {"i": 128, "zh": "识别", "en": "identify", "ipa": "[aɪˈdentɪfaɪ]", "pos": "v.", "gloss": "识别；辨认"},
    {"i": 129, "zh": "压力值", "en": "pressure", "ipa": "[ˈpreʃər]", "pos": "n.", "gloss": "压力；压强"},
    {"i": 130, "zh": "几何倍增", "en": "multiply", "ipa": "[ˈmʌltɪplaɪ]", "pos": "v.", "gloss": "倍增；繁殖"},
    {"i": 131, "zh": "复盘", "en": "reflect", "ipa": "[rɪˈflekt]", "pos": "v.", "gloss": "反思；回想"},
    {"i": 132, "zh": "躯体化", "en": "somatic", "ipa": "[soʊˈmætɪk]", "pos": "adj.", "gloss": "躯体的；身体的"},
    {"i": 133, "zh": "厌学", "en": "aversion", "ipa": "[əˈvɜːrʒn]", "pos": "n.", "gloss": "厌恶；反感"},
    {"i": 134, "zh": "一落千丈", "en": "plummet", "ipa": "[ˈplʌmɪt]", "pos": "v.", "gloss": "暴跌；骤降"},
    {"i": 135, "zh": "放弃", "en": "abandon", "ipa": "[əˈbændən]", "pos": "v.", "gloss": "放弃；抛弃"},
    {"i": 136, "skip": True},
    {"i": 137, "zh": "要强", "en": "ambitious", "ipa": "[æmˈbɪʃəs]", "pos": "adj.", "gloss": "有抱负的；要强的"},
    {"i": 138, "zh": "刮目相看", "en": "impress", "ipa": "[ɪmˈpres]", "pos": "v.", "gloss": "使印象深刻"},
    {"i": 139, "zh": "摸索", "en": "explore", "ipa": "[ɪkˈsplɔːr]", "pos": "v.", "gloss": "探索；摸索"},
    {"i": 140, "zh": "内耗", "en": "internal", "ipa": "[ɪnˈtɜːrnl]", "pos": "adj.", "gloss": "内部的；内在的"},
    {"i": 141, "zh": "愧疚", "en": "guilty", "ipa": "[ˈɡɪlti]", "pos": "adj.", "gloss": "愧疚的；有罪的"},
    {"i": 142, "zh": "讨好", "en": "appease", "ipa": "[əˈpiːz]", "pos": "v.", "gloss": "讨好；安抚"},
    {"i": 143, "skip": True},
    {"i": 144, "skip": True},
    {"i": 145, "zh": "清净", "en": "tranquil", "ipa": "[ˈtræŋkwɪl]", "pos": "adj.", "gloss": "安静的；平静的"},
    {"i": 146, "zh": "恩怨", "en": "grievance", "ipa": "[ˈɡriːvəns]", "pos": "n.", "gloss": "恩怨；不满"},
    {"i": 147, "zh": "紧绷", "en": "tense", "ipa": "[tens]", "pos": "adj.", "gloss": "紧绷的；紧张的"},
    {"i": 148, "zh": "奇迹", "en": "miracle", "ipa": "[ˈmɪrəkl]", "pos": "n.", "gloss": "奇迹"},
    {"i": 149, "zh": "引爆", "en": "detonate", "ipa": "[ˈdetəneɪt]", "pos": "v.", "gloss": "引爆；触发"},
    {"i": 150, "skip": True},
    {"i": 151, "zh": "加重", "en": "aggravate", "ipa": "[ˈæɡrəveɪt]", "pos": "v.", "gloss": "加重；恶化"},
    {"i": 152, "zh": "评论", "en": "comment", "ipa": "[ˈkɑːment]", "pos": "n.", "gloss": "评论；意见"},
    {"i": 153, "skip": True},
    {"i": 154, "zh": "发酵", "en": "ferment", "ipa": "[fərˈment]", "pos": "v.", "gloss": "发酵"},
    {"i": 155, "zh": "息息相关", "en": "intimately", "ipa": "[ˈɪntɪmətli]", "pos": "adv.", "gloss": "密切地； intimately"},
    {"i": 156, "zh": "首选", "en": "preferred", "ipa": "[prɪˈfɜːrd]", "pos": "adj.", "gloss": "首选的；偏爱的"},
    {"i": 157, "zh": "避免", "en": "avoid", "ipa": "[əˈvɔɪd]", "pos": "v.", "gloss": "避免；回避"},
    {"i": 158, "zh": "逐一", "en": "successively", "ipa": "[səkˈsesɪvli]", "pos": "adv.", "gloss": "逐一地；依次地"},
    {"i": 159, "zh": "日常", "en": "routine", "ipa": "[ruːˈtiːn]", "pos": "n.", "gloss": "日常；常规"},
    {"i": 160, "skip": True},
    {"i": 161, "zh": "调整", "en": "adjustment", "ipa": "[əˈdʒʌstmənt]", "pos": "n.", "gloss": "调整；适应"},
    {"i": 162, "zh": "秩序", "en": "order", "ipa": "[ˈɔːrdər]", "pos": "n.", "gloss": "秩序；顺序"},
    {"i": 163, "zh": "雷打不动", "en": "unwavering", "ipa": "[ʌnˈweɪvərɪŋ]", "pos": "adj.", "gloss": "坚定不移的"},
    {"i": 164, "zh": "奏效", "en": "effective", "ipa": "[ɪˈfektɪv]", "pos": "adj.", "gloss": "有效的"},
    {"i": 165, "skip": True},
    {"i": 166, "zh": "反应", "en": "response", "ipa": "[rɪˈspɑːns]", "pos": "n.", "gloss": "反应；回应"},
    {"i": 167, "zh": "顺其自然", "en": "resign", "ipa": "[rɪˈzaɪn]", "pos": "v.", "gloss": "顺从；听任"},
    {"i": 168, "skip": True},
    {"i": 169, "skip": True},
    {"i": 170, "zh": "歉意", "en": "apology", "ipa": "[əˈpɑːlədʒi]", "pos": "n.", "gloss": "歉意；道歉"},
    {"i": 171, "zh": "失利", "en": "defeat", "ipa": "[dɪˈfiːt]", "pos": "n.", "gloss": "失利；失败"},
    {"i": 172, "zh": "崩溃", "en": "desperate", "ipa": "[ˈdespərət]", "pos": "adj.", "gloss": "绝望的；不顾一切的"},
    {"i": 173, "skip": True},
    {"i": 174, "skip": True},
    {"i": 175, "zh": "声称", "en": "claim", "ipa": "[kleɪm]", "pos": "v.", "gloss": "声称；宣称"},
    {"i": 176, "zh": "偶然", "en": "accidentally", "ipa": "[ˌæksɪˈdentəli]", "pos": "adv.", "gloss": "偶然地；意外地"},
    {"i": 177, "skip": True},
    {"i": 178, "zh": "如释重负", "en": "relieved", "ipa": "[rɪˈliːvd]", "pos": "adj.", "gloss": "如释重负的"},
    {"i": 179, "zh": "白费", "en": "vain", "ipa": "[veɪn]", "pos": "adj.", "gloss": "徒劳的；无效的"},
    {"i": 180, "zh": "必需品", "en": "necessity", "ipa": "[nəˈsesəti]", "pos": "n.", "gloss": "必需品；必要"},
    {"i": 181, "zh": "按月", "en": "monthly", "ipa": "[ˈmʌnθli]", "pos": "adv.", "gloss": "按月；每月"},
    {"i": 182, "zh": "不存在", "en": "nonexistent", "ipa": "[ˌnɑːnɪɡˈzɪstənt]", "pos": "adj.", "gloss": "不存在的"},
    {"i": 183, "zh": "慌张", "en": "flustered", "ipa": "[ˈflʌstərd]", "pos": "adj.", "gloss": "慌张的；慌乱的"},
    {"i": 184, "zh": "驱使", "en": "compel", "ipa": "[kəmˈpel]", "pos": "v.", "gloss": "驱使；强迫"},
    {"i": 185, "zh": "样本", "en": "sample", "ipa": "[ˈsæmpl]", "pos": "n.", "gloss": "样本；样品"},
    {"i": 186, "zh": "消散", "en": "dissipate", "ipa": "[ˈdɪsɪpeɪt]", "pos": "v.", "gloss": "消散；驱散"},
    {"i": 187, "zh": "重建", "en": "reconstruction", "ipa": "[ˌriːkənˈstrʌkʃn]", "pos": "n.", "gloss": "重建；重构"},
    {"i": 188, "zh": "牵扯", "en": "involve", "ipa": "[ɪnˈvɑːlv]", "pos": "v.", "gloss": "涉及；牵扯"},
    {"i": 189, "skip": True},
    {"i": 190, "skip": True},
    {"i": 191, "zh": "区分", "en": "distinguish", "ipa": "[dɪˈstɪŋɡwɪʃ]", "pos": "v.", "gloss": "区分；辨别"},
    {"i": 192, "zh": "敏感", "en": "sensitive", "ipa": "[ˈsensətɪv]", "pos": "adj.", "gloss": "敏感的"},
    {"i": 193, "zh": "安抚", "en": "soothe", "ipa": "[suːð]", "pos": "v.", "gloss": "安抚；安慰"},
    {"i": 194, "zh": "自救", "en": "self-rescue", "ipa": "[ˌselfˈreskjuː]", "pos": "n.", "gloss": "自救"},
    {"i": 195, "zh": "紧绷", "en": "rigid", "ipa": "[ˈrɪdʒɪd]", "pos": "adj.", "gloss": "紧绷的；僵硬的"},
    {"i": 196, "skip": True},
    {"i": 197, "zh": "卸下", "en": "unload", "ipa": "[ʌnˈloʊd]", "pos": "v.", "gloss": "卸下；解除"},
    {"i": 198, "zh": "放纵", "en": "indulge", "ipa": "[ɪnˈdʌldʒ]", "pos": "v.", "gloss": "放纵；沉溺"},
    {"i": 199, "zh": "脱敏", "en": "desensitize", "ipa": "[ˌdiːˈsensɪtaɪz]", "pos": "v.", "gloss": "脱敏；降低敏感度"},
    {"i": 200, "zh": "强迫", "en": "force", "ipa": "[fɔːrs]", "pos": "v.", "gloss": "强迫；迫使"},
    {"i": 201, "zh": "突破口", "en": "breakthrough", "ipa": "[ˈbreɪkθruː]", "pos": "n.", "gloss": "突破；突破口"},
    {"i": 202, "skip": True},
    {"i": 203, "zh": "崩塌", "en": "crumble", "ipa": "[ˈkrʌmbl]", "pos": "v.", "gloss": "崩塌；瓦解"},
    {"i": 204, "zh": "不得不", "en": "compelled", "ipa": "[kəmˈpeld]", "pos": "adj.", "gloss": "被迫的；不得不的"},
    {"i": 205, "zh": "高强度", "en": "intense", "ipa": "[ɪnˈtens]", "pos": "adj.", "gloss": "高强度的；强烈的"},
    {"i": 206, "zh": "推送", "en": "push", "ipa": "[pʊʃ]", "pos": "v.", "gloss": "推送；推动"},
    {"i": 207, "zh": "抱怨", "en": "complaint", "ipa": "[kəmˈpleɪnt]", "pos": "n.", "gloss": "抱怨；投诉"},
    {"i": 208, "skip": True},
    {"i": 209, "skip": True},
    {"i": 210, "zh": "入职", "en": "onboard", "ipa": "[ˈɑːnbɔːrd]", "pos": "v.", "gloss": "入职；加入"},
    {"i": 211, "zh": "遇到", "en": "encounter", "ipa": "[ɪnˈkaʊntər]", "pos": "v.", "gloss": "遇到；邂逅"},
    {"i": 212, "zh": "告诉", "en": "inform", "ipa": "[ɪnˈfɔːrm]", "pos": "v.", "gloss": "告知；通知"},
    {"i": 213, "zh": "理解", "en": "empathy", "ipa": "[ˈempəθi]", "pos": "n.", "gloss": "理解；共情"},
    {"i": 214, "zh": "释然", "en": "relief", "ipa": "[rɪˈliːf]", "pos": "n.", "gloss": "释然；宽慰"},
    {"i": 215, "zh": "无力感", "en": "powerless", "ipa": "[ˈpaʊərləs]", "pos": "adj.", "gloss": "无力的；无能为力的"},
    {"i": 216, "zh": "体系", "en": "system", "ipa": "[ˈsɪstəm]", "pos": "n.", "gloss": "体系；系统"},
    {"i": 217, "zh": "争取", "en": "strive", "ipa": "[straɪv]", "pos": "v.", "gloss": "争取；努力"},
    {"i": 218, "zh": "健全", "en": "sound", "ipa": "[saʊnd]", "pos": "adj.", "gloss": "健全的；健康的"},
    {"i": 219, "zh": "权利", "en": "entitlement", "ipa": "[ɪnˈtaɪtlmənt]", "pos": "n.", "gloss": "权利；资格"},
    {"i": 220, "skip": True},
    {"i": 221, "zh": "苛责", "en": "criticism", "ipa": "[ˈkrɪtɪsɪzəm]", "pos": "n.", "gloss": "苛责；批评"},
    {"i": 222, "zh": "共情", "en": "compassion", "ipa": "[kəmˈpæʃn]", "pos": "n.", "gloss": "共情；同情"},
    {"i": 223, "zh": "了解", "en": "comprehend", "ipa": "[ˌkɑːmprɪˈhend]", "pos": "v.", "gloss": "了解；理解"},
    {"i": 224, "zh": "扶持", "en": "support", "ipa": "[səˈpɔːrt]", "pos": "n.", "gloss": "扶持；支持"},
    {"i": 225, "skip": True},
    {"i": 226, "skip": True},
    {"i": 227, "zh": "共性", "en": "commonality", "ipa": "[ˌkɑːməˈnæləti]", "pos": "n.", "gloss": "共性；共同点"},
    {"i": 228, "zh": "升学", "en": "advancement", "ipa": "[ədˈvænsmənt]", "pos": "n.", "gloss": "晋升；升学"},
    {"i": 229, "zh": "补足", "en": "compensate", "ipa": "[ˈkɑːmpenseɪt]", "pos": "v.", "gloss": "补偿；补足"},
    {"i": 230, "skip": True},
    {"i": 231, "zh": "挣扎", "en": "struggle", "ipa": "[ˈstrʌɡl]", "pos": "v.", "gloss": "挣扎；奋斗"},
    {"i": 232, "zh": "轻盈", "en": "graceful", "ipa": "[ˈɡreɪsfl]", "pos": "adj.", "gloss": "轻盈的；优雅的"},
    {"i": 233, "zh": "标准", "en": "criterion", "ipa": "[kraɪˈtɪriən]", "pos": "n.", "gloss": "标准；准则"},
    {"i": 234, "zh": "追求", "en": "pursuit", "ipa": "[pərˈsuːt]", "pos": "n.", "gloss": "追求；寻求"},
    {"i": 235, "zh": "支撑", "en": "sustain", "ipa": "[səˈsteɪn]", "pos": "v.", "gloss": "支撑；维持"},
    {"i": 236, "skip": True},
]

output = {"version": 1, "annotations": annotations}

with open("/Users/lzzg/code/news/content/drafts/ibs-young-people-dignity/llm_annotations.json", "w", encoding="utf-8") as f:
    json.dump(output, f, ensure_ascii=False, indent=2)

print(f"Written {len(annotations)} annotations")
non_skip = sum(1 for a in annotations if "skip" not in a)
print(f"Non-skip: {non_skip}/{len(annotations)} = {non_skip/len(annotations)*100:.1f}%")
