#!/usr/bin/env python3
"""
Global default lexicon for annotate_engine=keywords.

Each tuple is (zh_substring, en, ipa, pos, gloss). Sorted by longest zh first for
longest-match in annotate_lib.pick_keyword. Extend _KEYWORD_ENTRIES only; do not
hand-edit KEYWORD_LEXICON order.
"""
from __future__ import annotations

_KEYWORD_ENTRIES: list[tuple[str, str, str, str, str]] = [
        ("国内政治秩序", "domestic-order", "[dəˈmestɪk ˈɔːdə]", "n.", "国内政治秩序"),
        ("地缘政治秩序", "geopolitical-order", "[ˌdʒiːəʊpəˈlɪtɪkl ˈɔːdə]", "n.", "地缘政治秩序"),
        ("世界储备货币", "world-reserve-currency", "[wɜːld rɪˈzɜːv ˈkʌrənsi]", "n.", "世界/全球储备货币（如美元）"),
        ("偿债支出", "debt-service", "[det ˈsɜːvɪs]", "n.", "偿债支出（本息偿付负担）"),
        ("供需失衡", "disequilibrium", "[ˌdɪsiːkwɪˈlɪbriəm]", "n.", "失衡"),
        ("地缘政治", "geopolitics", "[ˌdʒiːəʊpəˈlɪtɪks]", "n.", "地缘政治"),
        ("政治极化", "polarization", "[ˌpəʊləraɪˈzeɪʃn]", "n.", "政治极化"),
        ("民粹主义", "populism", "[ˈpɒpjəlɪzəm]", "n.", "民粹主义"),
        ("专制统治", "autocracy", "[ɔːˈtɒkrəsi]", "n.", "专制统治"),
        ("政治秩序", "political-order", "[pəˈlɪtɪkl ˈɔːdə]", "n.", "政治秩序"),
        ("货币秩序", "monetary-order", "[ˈmʌnɪtri ˈɔːdə]", "n.", "货币秩序"),
        ("货币体系", "monetary-system", "[ˈmʌnɪtri ˈsɪstəm]", "n.", "货币体系"),
        ("资本市场", "capital-markets", "[ˈkæpɪtl ˈmɑːkɪts]", "n.", "资本市场"),
        ("财政窟窿", "fiscal-gap", "[ˈfɪskl ɡæp]", "n.", "财政缺口（窟窿）"),
        ("储备货币", "currency", "[ˈkʌrənsi]", "n.", "储备货币（央行持有的外币资产）"),
        ("大周期", "mega-cycle", "[ˈmeɡə saɪkl]", "n.", "大周期"),
        ("秩序崩溃", "order-breakdown", "[ˈɔːdə ˈbreɪkdaʊn]", "n.", "秩序崩溃、瓦解"),
        ("黄金暴涨", "gold-surge", "[ɡəʊld sɜːdʒ]", "n.", "黄金价格暴涨"),
        ("地缘博弈", "geopolitical-rivalry", "[ˌdʒiːəʊpəˈlɪtɪkl ˈraɪvlri]", "n.", "地缘战略博弈"),
        ("周期透镜", "cyclical-lens", "[ˈsaɪklɪkl lenz]", "n.", "周期透镜（观察框架）"),
        ("国内政治", "politics", "[ˈpɒlɪtɪks]", "n.", "国内政治"),
        ("动态变化", "dynamic-change", "[daɪˈnæmɪk tʃeɪndʒ]", "n.", "动态变化"),
        ("多边体系", "multilateralism", "[ˌmʌltɪˈlætərəlɪzəm]", "n.", "多边体系/多边主义"),
        ("强制执行", "enforcement", "[ɪnˈfɔːsmənt]", "n.", "执行机制"),
        ("财富差距", "wealth-gap", "[welθ ɡæp]", "n.", "贫富差距"),
        ("民主制度", "democracy", "[dɪˈmɒkrəsi]", "n.", "民主制度"),
        ("司法系统", "judiciary", "[dʒuːˈdɪʃəri]", "n.", "司法体系"),
        ("最高法院", "Court", "[kɔːt]", "n.", "最高法院"),
        ("自然灾害", "disasters", "[dɪˈzɑːstəz]", "n.", "自然灾害"),
        ("科技战", "tech-war", "[tek wɔː]", "n.", "科技战、科技竞争"),
        ("美元贬值", "dollar-devaluation", "[ˈdɒlə ˌdiːvæljuˈeɪʃn]", "n.", "美元贬值"),
        ("债务循环", "debt-cycle", "[det ˈsaɪkl]", "n.", "债务周期"),
        ("债务", "debt", "[det]", "n.", "债务（负债规模）"),
        ("印钞", "printing", "[ˈprɪntɪŋ]", "n.", "印钞"),
        ("借贷", "borrowing", "[ˈbɒrəʊɪŋ]", "n.", "借贷"),
        ("信用", "credit", "[ˈkredɪt]", "n.", "信用"),
        ("生产力", "productivity", "[ˌprɒdʌkˈtɪvəti]", "n.", "生产率"),
        ("崩溃机制", "collapse", "[kəˈlæps]", "n.", "崩溃机制"),
        ("崩溃", "implosion", "[ɪmˈpləʊʒn]", "n.", "内爆式崩溃"),
        ("秩序", "order", "[ˈɔːdə]", "n.", "秩序"),
        ("体系", "system", "[ˈsɪstəm]", "n.", "体系"),
        ("极化", "polarization", "[ˌpəʊləraɪˈzeɪʃn]", "n.", "极化"),
        ("动荡", "turbulence", "[ˈtɜːbjələns]", "n.", "动荡"),
        ("资产", "assets", "[ˈæsets]", "n.", "资产"),
        ("机遇", "upside", "[ˈʌpsaɪd]", "n.", "上行空间"),
        ("症状", "symptom", "[ˈsɪmptəm]", "n.", "症状"),
        ("逻辑", "logic", "[ˈlɒdʒɪk]", "n.", "逻辑"),
        ("力量", "forces", "[ˈfɔːsɪz]", "n.", "力量"),
        ("机制", "mechanism", "[ˈmekənɪzəm]", "n.", "机制"),
        ("动态", "dynamics", "[daɪˈnæmɪks]", "n.", "动态"),
        ("运作", "operation", "[ˌɒpəˈreɪʃn]", "n.", "运作"),
        ("运转", "operation", "[ˌɒpəˈreɪʃn]", "n.", "运转"),
        ("风险", "peril", "[ˈperəl]", "n.", "风险"),
        ("失衡", "imbalance", "[ɪmˈbæləns]", "n.", "失衡"),
        ("演变", "evolution", "[ˌiːvəˈluːʃn]", "n.", "演变"),
        ("妥协", "compromise", "[ˈkɒmprəmaɪz]", "n.", "妥协"),
        ("僵局", "deadlock", "[ˈdedlɒk]", "n.", "僵局"),
        ("繁荣", "prosperity", "[prɒˈsperəti]", "n.", "繁荣"),
        ("战争", "warfare", "[ˈwɔːfeə]", "n.", "战争"),
        ("发明", "invention", "[ɪnˈvenʃn]", "n.", "发明"),
        ("干旱", "drought", "[draʊt]", "n.", "干旱"),
        ("洪水", "flooding", "[ˈflʌdɪŋ]", "n.", "洪水"),
        ("疫情", "pandemic", "[pænˈdemɪk]", "n.", "大流行病"),
        ("储备", "stockpile", "[ˈstɒkpaɪl]", "n.", "储备"),
        ("关税", "tariff", "[ˈtærɪf]", "n.", "关税"),
        ("制裁", "sanctions", "[ˈsæŋkʃnz]", "n.", "制裁"),
        ("供应链", "supply-chain", "[səˈplaɪ tʃeɪn]", "n.", "供应链"),
        ("全方位的品牌出海解决方案", "go-global-solution", "[ɡəʊ ˈɡləʊbl səˈluːʃn]", "n.", "品牌出海一揽子方案"),
        ("品牌出海解决方案", "brand-go-global-solution", "[brænd ɡəʊ ˈɡləʊbl səˈluːʃn]", "n.", "品牌出海方案"),
        ("国内国际双循环", "dual-circulation", "[djuːəl ˌsɜːkjʊˈleɪʃn]", "n.", "国内国际双循环"),
        ("产业转型升级", "industrial-upgrade", "[ɪnˈdʌstriəl ˈʌpɡreɪd]", "n.", "产业转型升级"),
        ("全球定价权", "global-pricing-power", "[ˈɡləʊbl ˈpraɪsɪŋ ˈpaʊə]", "n.", "全球定价权"),
        ("可持续增长", "sustainable-growth", "[səˈsteɪnəbl ɡrəʊθ]", "n.", "可持续增长"),
        ("财报电话会", "earnings-call", "[ˈɜːnɪŋz kɔːl]", "n.", "财报电话会"),
        ("新发展格局", "new-development-paradigm", "[njuː dɪˈveləpmənt ˈpærədaɪm]", "n.", "新发展格局"),
        ("国内大循环", "domestic-loop", "[dəˈmestɪk luːp]", "n.", "国内大循环"),
        ("战略性布局", "strategic-layout", "[strəˈtiːdʒɪk ˈlaɪaʊt]", "n.", "战略性布局"),
        ("流量红利", "traffic-dividend", "[ˈtræfɪk ˈdɪvɪdənd]", "n.", "流量红利"),
        ("平台生态", "platform-ecosystem", "[ˈplætfɔːm ˈiːkəʊsɪstəm]", "n.", "平台生态"),
        ("半托管", "semi-consignment", "[ˈsemi kənˈsaɪnmənt]", "n.", "半托管（平台模式）"),
        ("全托管", "full-consignment", "[fʊl kənˈsaɪnmənt]", "n.", "全托管（平台履约）"),
        ("产业带", "industrial-belt", "[ɪnˈdʌstriəl belt]", "n.", "产业带"),
        ("中国制造", "made-in-China", "[meɪd ɪn ˈtʃaɪnə]", "n.", "中国制造"),
        ("代工厂", "contract-factory", "[ˈkɒntrækt ˈfæktəri]", "n.", "代工厂"),
        ("价值链", "value-chain", "[ˈvæljuː tʃeɪn]", "n.", "价值链"),
        ("基础设施", "infrastructure", "[ˈɪnfrəstrʌktʃə]", "n.", "基础设施"),
        ("品牌出海", "brand-go-global", "[brænd ɡəʊ ˈɡləʊbl]", "n.", "品牌出海"),
        ("数字化", "digitalization", "[ˌdɪdʒɪtəlaɪˈzeɪʃn]", "n.", "数字化"),
        ("净利润", "net-profit", "[net ˈprɒfɪt]", "n.", "净利润"),
        ("财报", "earnings-report", "[ˈɜːnɪŋz rɪˈpɔːt]", "n.", "财报"),
        ("营收", "revenue", "[ˈrevənjuː]", "n.", "营收"),
        ("赋能", "empowerment", "[ɪmˈpaʊəmənt]", "n.", "赋能"),
        ("跃迁", "step-change", "[step tʃeɪndʒ]", "n.", "跃迁、阶跃"),
        ("跨境", "cross-border", "[krɒs ˈbɔːdə]", "adj.", "跨境"),
        ("合规", "compliance", "[kəmˈplaɪəns]", "n.", "合规"),
        ("代工", "OEM", "[ˌəʊ iː ˈem]", "n.", "代工（OEM）"),
        ("商家", "merchant", "[ˈmɜːtʃənt]", "n.", "商家"),
        ("定制化制造方案", "custom-manufacturing", "[ˈkʌstəm ˌmænjʊˈfæktʃərɪŋ]", "n.", "定制化制造"),
        ("系统性迭代", "systemic-iteration", "[sɪˈstemɪk ˌɪtəˈreɪʃn]", "n.", "系统性迭代"),
        ("规模化跃迁", "scaling-leap", "[ˈskeɪlɪŋ liːp]", "n.", "规模化跃迁"),
        ("产业红利", "industry-dividend", "[ˈɪndəstri ˈdɪvɪdənd]", "n.", "产业红利"),
        ("标准出海", "standards-go-global", "[ˈstændədz ɡəʊ ˈɡləʊbl]", "n.", "标准出海"),
        ("商品出海", "goods-go-global", "[ɡʊdz ɡəʊ ˈɡləʊbl]", "n.", "商品出海"),
        ("海外订单", "overseas-orders", "[ˌəʊvəˈsiːz ˈɔːdəz]", "n.", "海外订单"),
        ("治理架构", "governance-structure", "[ˈɡʌvənəns strʌktʃə]", "n.", "治理架构"),
        ("产业杠杆", "industry-leverage", "[ˈɪndəstri ˈlevərɪdʒ]", "n.", "产业杠杆"),
        ("流量杠杆", "traffic-leverage", "[ˈtræfɪk ˈlevərɪdʒ]", "n.", "流量杠杆"),
        ("复制粘贴", "copy-paste", "[ˈkɒpi peɪst]", "n.", "复制粘贴"),
        ("质价比", "price-performance", "[ˈpraɪs pəˈfɔːməns]", "n.", "质价比"),
        ("爆款", "hit-product", "[hɪt ˈprɒdʌkt]", "n.", "爆款"),
        ("自营品牌", "private-label-brand", "[ˈpraɪvət ˈleɪbl brænd]", "n.", "自营品牌"),
        ("专项公司", "project-entity", "[ˈprɒdʒekt ˈentəti]", "n.", "专项/项目公司"),
        ("价格竞争", "price-competition", "[ˈpraɪs ˌkɒmpəˈtɪʃn]", "n.", "价格竞争"),
        ("新质品牌", "next-gen-brand", "[nekst dʒen brænd]", "n.", "新质品牌"),
        ("新质产品", "next-gen-product", "[nekst dʒen ˈprɒdʌkt]", "n.", "新质产品"),
        ("生产周期", "production-cycle", "[prəˈdʌkʃn saɪkl]", "n.", "生产周期"),
        ("工艺流程", "process-flow", "[ˈprəʊses fləʊ]", "n.", "工艺流程"),
        ("试错", "trial-and-error", "[traɪəl ən ˈerə]", "n.", "试错"),
        ("可复用", "reusability", "[ˌriːjuːzəˈbɪləti]", "n.", "可复用性"),
        ("数据驱动", "data-driven", "[ˈdeɪtə ˈdrɪvn]", "adj.", "数据驱动"),
        ("电商", "e-commerce", "[ˈiː kɒmɜːs]", "n.", "电子商务"),
        ("通胀", "inflation", "[ɪnˈfleɪʃn]", "n.", "通胀"),
        ("利率", "rates", "[reɪts]", "n.", "利率"),
        ("财政", "fiscal", "[ˈfɪskl]", "adj.", "财政的"),
        ("货币", "monetary", "[ˈmʌnɪtri]", "adj.", "货币的"),
        ("霸权", "hegemony", "[hɪˈɡeməni]", "n.", "霸权"),
        ("海峡", "strait", "[streɪt]", "n.", "海峡"),
        ("霍尔木兹", "Hormuz", "[hɔːˈmuːz]", "n.", "霍尔木兹（地名）"),
        ("内战", "strife", "[straɪf]", "n.", "内乱"),
        ("魏玛", "Weimar", "[ˈvaɪmɑː]", "n.", "魏玛"),
        ("元老院", "Senate", "[ˈsenɪt]", "n.", "元老院"),
        ("理想国", "Republic", "[rɪˈpʌblɪk]", "n.", "《理想国》"),
        ("联合国", "UN", "[ˌjuː ˈen]", "n.", "联合国"),
        ("世贸组织", "WTO", "[ˌdʌbəljuː tiː ˈəʊ]", "n.", "世贸组织"),
        ("国际法院", "tribunal", "[traɪˈbjuːnl]", "n.", "国际法院"),
        ("AI", "AI", "[ˌeɪ ˈaɪ]", "n.", "人工智能"),
        ("技术", "technology", "[tekˈnɒlədʒi]", "n.", "技术"),
        ("奇迹", "miracle", "[ˈmɪrəkl]", "n.", "奇迹"),
        ("压力", "headwinds", "[ˈhedwɪndz]", "n.", "逆风"),
        ("阶段", "phase", "[feɪz]", "n.", "阶段"),
        ("诊断", "diagnosis", "[ˌdaɪəɡˈnəʊsɪs]", "n.", "诊断"),
        ("预演", "precursor", "[priːˈkɜːsə]", "n.", "先兆"),
        ("万能药", "panacea", "[ˌpænəˈsiːə]", "n.", "万灵药"),
        ("普通人", "layperson", "[ˈleɪpɜːsn]", "n.", "普通人"),
        ("配置", "allocation", "[ˌæləˈkeɪʃn]", "n.", "配置"),
        ("多元化", "diversification", "[daɪˌvɜːsɪfɪˈkeɪʃn]", "n.", "分散化"),
        ("黄金", "bullion", "[ˈbʊliən]", "n.", "贵金属条块"),
        ("美元", "greenback", "[ˈɡriːnbæk]", "n.", "美元（口语）"),
        ("桥水", "Bridgewater", "[ˈbrɪdʒwɔːtə]", "n.", "桥水基金"),
        ("达利欧", "Dalio", "[ˈdɑːliəʊ]", "n.", "达利欧"),
        ("华尔街见闻", "Wallstreetcn", "[wɔːl striːt siː en]", "n.", "华尔街见闻"),
        ("底线思维", "Dixiansiwei", "[ˌdiːʃiːənˈsɪweɪ]", "n.", "底线思维（媒体名）"),
        ("笔记侠", "Bijixia", "[biː dʒiː ʃiːə]", "n.", "笔记侠（公号名）"),
        ("独立观点", "independent", "[ˌɪndɪˈpendənt]", "adj.", "独立观点"),
        ("立场", "stance", "[stæns]", "n.", "立场"),
        ("韵脚", "rhyme", "[raɪm]", "n.", "韵脚"),
]

KEYWORD_LEXICON: list[tuple[str, str, str, str, str]] = sorted(
    _KEYWORD_ENTRIES,
    key=lambda x: len(x[0]),
    reverse=True,
)
